/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'
import { Route as AuthenticatedStudioAiRouteImport } from './routes/_authenticated/studio.ai'
import { Route as AuthenticatedStudioAnalyticsRouteImport } from './routes/_authenticated/studio.analytics'
import { Route as AuthenticatedStudioArticlesRouteImport } from './routes/_authenticated/studio.articles'
import { Route as AuthenticatedStudioContentRouteImport } from './routes/_authenticated/studio.content'
import { Route as AuthenticatedStudioDeveloperRouteImport } from './routes/_authenticated/studio.developer'
import { Route as AuthenticatedStudioExperienceRouteImport } from './routes/_authenticated/studio.experience'
import { Route as AuthenticatedStudioHqTerminalRouteImport } from './routes/_authenticated/studio.hq-terminal'
import { Route as AuthenticatedStudioMediaRouteImport } from './routes/_authenticated/studio.media'
import { Route as AuthenticatedStudioProjectsRouteImport } from './routes/_authenticated/studio.projects'
import { Route as AuthenticatedStudioSeoRouteImport } from './routes/_authenticated/studio.seo'
import { Route as AuthenticatedStudioSettingsRouteImport } from './routes/_authenticated/studio.settings'
import { Route as AuthenticatedStudioSkillsRouteImport } from './routes/_authenticated/studio.skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioAiRoute = AuthenticatedStudioAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedStudioRoute,
} as any)
const AuthenticatedStudioAnalyticsRoute =
  AuthenticatedStudioAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioArticlesRoute =
  AuthenticatedStudioArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioContentRoute =
  AuthenticatedStudioContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioDeveloperRoute =
  AuthenticatedStudioDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioExperienceRoute =
  AuthenticatedStudioExperienceRouteImport.update({
    id: '/experience',
    path: '/experience',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioHqTerminalRoute =
  AuthenticatedStudioHqTerminalRouteImport.update({
    id: '/hq-terminal',
    path: '/hq-terminal',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioMediaRoute =
  AuthenticatedStudioMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioProjectsRoute =
  AuthenticatedStudioProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioSeoRoute = AuthenticatedStudioSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedStudioRoute,
} as any)
const AuthenticatedStudioSettingsRoute =
  AuthenticatedStudioSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioSkillsRoute =
  AuthenticatedStudioSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/recruiter': typeof RecruiterRoute
  '/studio': typeof AuthenticatedStudioRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/studio/ai': typeof AuthenticatedStudioAiRoute
  '/studio/analytics': typeof AuthenticatedStudioAnalyticsRoute
  '/studio/articles': typeof AuthenticatedStudioArticlesRoute
  '/studio/content': typeof AuthenticatedStudioContentRoute
  '/studio/developer': typeof AuthenticatedStudioDeveloperRoute
  '/studio/experience': typeof AuthenticatedStudioExperienceRoute
  '/studio/hq-terminal': typeof AuthenticatedStudioHqTerminalRoute
  '/studio/media': typeof AuthenticatedStudioMediaRoute
  '/studio/projects': typeof AuthenticatedStudioProjectsRoute
  '/studio/seo': typeof AuthenticatedStudioSeoRoute
  '/studio/settings': typeof AuthenticatedStudioSettingsRoute
  '/studio/skills': typeof AuthenticatedStudioSkillsRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/recruiter': typeof RecruiterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/studio/ai': typeof AuthenticatedStudioAiRoute
  '/studio/analytics': typeof AuthenticatedStudioAnalyticsRoute
  '/studio/articles': typeof AuthenticatedStudioArticlesRoute
  '/studio/content': typeof AuthenticatedStudioContentRoute
  '/studio/developer': typeof AuthenticatedStudioDeveloperRoute
  '/studio/experience': typeof AuthenticatedStudioExperienceRoute
  '/studio/hq-terminal': typeof AuthenticatedStudioHqTerminalRoute
  '/studio/media': typeof AuthenticatedStudioMediaRoute
  '/studio/projects': typeof AuthenticatedStudioProjectsRoute
  '/studio/seo': typeof AuthenticatedStudioSeoRoute
  '/studio/settings': typeof AuthenticatedStudioSettingsRoute
  '/studio/skills': typeof AuthenticatedStudioSkillsRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/recruiter': typeof RecruiterRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/_authenticated/studio/ai': typeof AuthenticatedStudioAiRoute
  '/_authenticated/studio/analytics': typeof AuthenticatedStudioAnalyticsRoute
  '/_authenticated/studio/articles': typeof AuthenticatedStudioArticlesRoute
  '/_authenticated/studio/content': typeof AuthenticatedStudioContentRoute
  '/_authenticated/studio/developer': typeof AuthenticatedStudioDeveloperRoute
  '/_authenticated/studio/experience': typeof AuthenticatedStudioExperienceRoute
  '/_authenticated/studio/hq-terminal': typeof AuthenticatedStudioHqTerminalRoute
  '/_authenticated/studio/media': typeof AuthenticatedStudioMediaRoute
  '/_authenticated/studio/projects': typeof AuthenticatedStudioProjectsRoute
  '/_authenticated/studio/seo': typeof AuthenticatedStudioSeoRoute
  '/_authenticated/studio/settings': typeof AuthenticatedStudioSettingsRoute
  '/_authenticated/studio/skills': typeof AuthenticatedStudioSkillsRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/recruiter'
    | '/studio'
    | '/blog/$slug'
    | '/studio/ai'
    | '/studio/analytics'
    | '/studio/articles'
    | '/studio/content'
    | '/studio/developer'
    | '/studio/experience'
    | '/studio/hq-terminal'
    | '/studio/media'
    | '/studio/projects'
    | '/studio/seo'
    | '/studio/settings'
    | '/studio/skills'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/recruiter'
    | '/blog/$slug'
    | '/studio/ai'
    | '/studio/analytics'
    | '/studio/articles'
    | '/studio/content'
    | '/studio/developer'
    | '/studio/experience'
    | '/studio/hq-terminal'
    | '/studio/media'
    | '/studio/projects'
    | '/studio/seo'
    | '/studio/settings'
    | '/studio/skills'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/recruiter'
    | '/_authenticated/studio'
    | '/blog/$slug'
    | '/_authenticated/studio/ai'
    | '/_authenticated/studio/analytics'
    | '/_authenticated/studio/articles'
    | '/_authenticated/studio/content'
    | '/_authenticated/studio/developer'
    | '/_authenticated/studio/experience'
    | '/_authenticated/studio/hq-terminal'
    | '/_authenticated/studio/media'
    | '/_authenticated/studio/projects'
    | '/_authenticated/studio/seo'
    | '/_authenticated/studio/settings'
    | '/_authenticated/studio/skills'
    | '/_authenticated/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  RecruiterRoute: typeof RecruiterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/ai': {
      id: '/_authenticated/studio/ai'
      path: '/ai'
      fullPath: '/studio/ai'
      preLoaderRoute: typeof AuthenticatedStudioAiRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/analytics': {
      id: '/_authenticated/studio/analytics'
      path: '/analytics'
      fullPath: '/studio/analytics'
      preLoaderRoute: typeof AuthenticatedStudioAnalyticsRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/articles': {
      id: '/_authenticated/studio/articles'
      path: '/articles'
      fullPath: '/studio/articles'
      preLoaderRoute: typeof AuthenticatedStudioArticlesRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/content': {
      id: '/_authenticated/studio/content'
      path: '/content'
      fullPath: '/studio/content'
      preLoaderRoute: typeof AuthenticatedStudioContentRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/developer': {
      id: '/_authenticated/studio/developer'
      path: '/developer'
      fullPath: '/studio/developer'
      preLoaderRoute: typeof AuthenticatedStudioDeveloperRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/experience': {
      id: '/_authenticated/studio/experience'
      path: '/experience'
      fullPath: '/studio/experience'
      preLoaderRoute: typeof AuthenticatedStudioExperienceRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/hq-terminal': {
      id: '/_authenticated/studio/hq-terminal'
      path: '/hq-terminal'
      fullPath: '/studio/hq-terminal'
      preLoaderRoute: typeof AuthenticatedStudioHqTerminalRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/media': {
      id: '/_authenticated/studio/media'
      path: '/media'
      fullPath: '/studio/media'
      preLoaderRoute: typeof AuthenticatedStudioMediaRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/projects': {
      id: '/_authenticated/studio/projects'
      path: '/projects'
      fullPath: '/studio/projects'
      preLoaderRoute: typeof AuthenticatedStudioProjectsRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/seo': {
      id: '/_authenticated/studio/seo'
      path: '/seo'
      fullPath: '/studio/seo'
      preLoaderRoute: typeof AuthenticatedStudioSeoRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/settings': {
      id: '/_authenticated/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof AuthenticatedStudioSettingsRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/skills': {
      id: '/_authenticated/studio/skills'
      path: '/skills'
      fullPath: '/studio/skills'
      preLoaderRoute: typeof AuthenticatedStudioSkillsRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
  }
}

interface AuthenticatedStudioRouteChildren {
  AuthenticatedStudioAiRoute: typeof AuthenticatedStudioAiRoute
  AuthenticatedStudioAnalyticsRoute: typeof AuthenticatedStudioAnalyticsRoute
  AuthenticatedStudioArticlesRoute: typeof AuthenticatedStudioArticlesRoute
  AuthenticatedStudioContentRoute: typeof AuthenticatedStudioContentRoute
  AuthenticatedStudioDeveloperRoute: typeof AuthenticatedStudioDeveloperRoute
  AuthenticatedStudioExperienceRoute: typeof AuthenticatedStudioExperienceRoute
  AuthenticatedStudioHqTerminalRoute: typeof AuthenticatedStudioHqTerminalRoute
  AuthenticatedStudioMediaRoute: typeof AuthenticatedStudioMediaRoute
  AuthenticatedStudioProjectsRoute: typeof AuthenticatedStudioProjectsRoute
  AuthenticatedStudioSeoRoute: typeof AuthenticatedStudioSeoRoute
  AuthenticatedStudioSettingsRoute: typeof AuthenticatedStudioSettingsRoute
  AuthenticatedStudioSkillsRoute: typeof AuthenticatedStudioSkillsRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedStudioRouteChildren: AuthenticatedStudioRouteChildren = {
  AuthenticatedStudioAiRoute: AuthenticatedStudioAiRoute,
  AuthenticatedStudioAnalyticsRoute: AuthenticatedStudioAnalyticsRoute,
  AuthenticatedStudioArticlesRoute: AuthenticatedStudioArticlesRoute,
  AuthenticatedStudioContentRoute: AuthenticatedStudioContentRoute,
  AuthenticatedStudioDeveloperRoute: AuthenticatedStudioDeveloperRoute,
  AuthenticatedStudioExperienceRoute: AuthenticatedStudioExperienceRoute,
  AuthenticatedStudioHqTerminalRoute: AuthenticatedStudioHqTerminalRoute,
  AuthenticatedStudioMediaRoute: AuthenticatedStudioMediaRoute,
  AuthenticatedStudioProjectsRoute: AuthenticatedStudioProjectsRoute,
  AuthenticatedStudioSeoRoute: AuthenticatedStudioSeoRoute,
  AuthenticatedStudioSettingsRoute: AuthenticatedStudioSettingsRoute,
  AuthenticatedStudioSkillsRoute: AuthenticatedStudioSkillsRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedStudioRouteWithChildren =
  AuthenticatedStudioRoute._addFileChildren(AuthenticatedStudioRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioRoute: AuthenticatedStudioRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  RecruiterRoute: RecruiterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
